name: Tests
on: push
jobs:
  test:
      name: Run tests
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - name: Install        
        run: yarn install
      - name: Test
        run: yarn test        